<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SZ-00343555-01" failures="1" tests="2" name="Dong&#039;s测试模块" time="0.683" errors="0" timestamp="04 8月 2022 08:38:33 GMT">
  <testcase classname="testcase.TestDemo" name="test1" time="0.101">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at testcase.TestDemo.test1(TestDemo.java:38)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="testcase.TestDemo" name="testGet" time="0.378"/>
</testsuite> <!-- Dong's测试模块 -->
