<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="SZ-00343555-01" failures="2" tests="10" name="Dong&#039;s测试模块" time="5.62" errors="0" timestamp="12 8月 2022 08:42:00 GMT">
  <testcase classname="testcase.TestDemo" name="checkMapNotNull" time="0.986"/>
  <testcase classname="testcase.TestDemo" name="test" time="0.002"/>
  <testcase classname="testcase.TestDemo" name="test" time="0.001"/>
  <testcase classname="testcase.TestDemo" name="test" time="0.001"/>
  <testcase classname="testcase.TestDemo" name="test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at testcase.TestDemo.test1(TestDemo.java:21)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="testcase.TestDemo" name="testHttpGet" time="1.318"/>
  <testcase classname="testcase.TestDemo" name="testHttpPost" time="0.032"/>
  <testcase classname="testcase.TestDemo" name="testHttpPostMap" time="0.003"/>
  <testcase classname="testcase.TestDemo" name="testTimeOut" time="3.024">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testcase.TestDemo.testTimeOut() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testcase.TestDemo.testTimeOut() didn't finish within the time-out 3000
	at java.base@17.0.3.1/java.util.Arrays.copyOf(Arrays.java:3537)
	at java.base@17.0.3.1/java.lang.String.encodeUTF8(String.java:1265)
	at java.base@17.0.3.1/java.lang.String.encode(String.java:825)
	at java.base@17.0.3.1/java.lang.String.getBytes(String.java:1803)
	at app//testcase.TestDemo.testTimeOut(TestDemo.java:132)
	at java.base@17.0.3.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.3.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.3.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.3.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.3.1/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- testTimeOut -->
  <testcase classname="testcase.TestFileUtil" name="testFileUtils" time="0.0">
    <skipped/>
  </testcase> <!-- testFileUtils -->
  <testcase classname="testcase.TestDemo" name="testOkHttpGet" time="0.0">
    <ignored/>
  </testcase> <!-- testOkHttpGet -->
</testsuite> <!-- Dong's测试模块 -->
